#!/usr/bin/env tsx
/**
 * One-shot extractor: pull site coordinates from v1's Django database and
 * emit a `config/sites.yaml` file keyed on the single-token site code that
 * matches `:Site.name` in the v2 Neo4j graph (produced by parseHostname).
 *
 * WHY THIS IS A ONE-SHOT, not part of the nightly ingest:
 *   - v1 holds curated latitude/longitude per site in `sites_portal` / the
 *     `gis_helpers/` module. These are operator facility coordinates, not
 *     device-count-weighted averages.
 *   - We don't want a runtime dependency on v1's Django DB — v2 is
 *     decoupling from v1. Capture the coords once, commit the YAML,
 *     re-run only when the operator adds a new site.
 *
 * HOW TO RUN (requires access to the v1 machine):
 *
 *   V1_DATABASE_URL=postgresql://user:pass@v1-host:5432/portal \
 *     pnpm tsx scripts/extract-v1-sites.ts > config/sites.yaml
 *
 * PRE-REQUISITES:
 *   - Read access to the v1 database. The SQL below SELECTS from
 *     `sites_portal` — adapt if the v1 table names differ.
 *   - The `pg` npm package (already a workspace dependency via ingestor).
 *
 * WHAT IT EMITS:
 *   A sites.yaml document with the same shape as the committed starter
 *   file — `sites:` mapping from single-token code to `{ lat, lng, region }`.
 *
 * Safe to run multiple times — idempotent (pure query + serialize, no writes).
 */

import pg from "pg";
import { stringify } from "yaml";

const { Client } = pg;

type V1SiteRow = {
  site_code: string | null;
  latitude: string | number | null;
  longitude: string | number | null;
  region: string | null;
};

async function main(): Promise<void> {
  const url = process.env.V1_DATABASE_URL;
  if (!url) {
    process.stderr.write(
      "V1_DATABASE_URL not set — cannot extract from v1.\n" +
        "Set it to the v1 Postgres connection string and re-run.\n",
    );
    process.exit(2);
  }

  const client = new Client({ connectionString: url });
  await client.connect();
  let rows: V1SiteRow[];
  try {
    // ADAPT THIS QUERY — the v1 schema is not shipped with v2 so we can't
    // verify column names from here. Confirm `site_code` is the single-
    // token canonical site identifier (matches parseHostname output) and
    // not the two-token prefix some v1 views expose.
    const result = await client.query<V1SiteRow>(
      `SELECT site_code, latitude, longitude, region
         FROM sites_portal
        WHERE latitude  IS NOT NULL
          AND longitude IS NOT NULL
          AND site_code IS NOT NULL`,
    );
    rows = result.rows;
  } finally {
    await client.end();
  }

  const sites: Record<string, { lat: number; lng: number; region?: string }> =
    {};
  for (const r of rows) {
    if (r.site_code == null) continue;
    const lat = typeof r.latitude === "string" ? Number(r.latitude) : r.latitude;
    const lng = typeof r.longitude === "string" ? Number(r.longitude) : r.longitude;
    if (lat == null || lng == null) continue;
    if (!Number.isFinite(lat) || !Number.isFinite(lng)) continue;
    if (lat < -90 || lat > 90 || lng < -180 || lng > 180) continue;

    const entry: { lat: number; lng: number; region?: string } = { lat, lng };
    if (r.region) entry.region = r.region;
    sites[r.site_code] = entry;
  }

  const yamlOut = stringify(
    { sites },
    { lineWidth: 0, defaultKeyType: "PLAIN", flowCollectionPadding: false },
  );
  process.stdout.write(
    "# Generated by scripts/extract-v1-sites.ts.\n" +
      `# Source rows: ${rows.length}; valid: ${Object.keys(sites).length}.\n` +
      "# Edit by hand only for one-off corrections; re-run the extractor\n" +
      "# to re-sync from v1.\n" +
      yamlOut,
  );
}

main().catch((err) => {
  process.stderr.write(`extract-v1-sites failed: ${err.message}\n`);
  process.exit(1);
});
